#!/bin/bash

checkRoot(){

	if [[ ${EUID} -ne '0' ]]; then

		echo "Run me as root!"
		exit 1

	fi
}

installAptPkgs(){

	apt update

	PKGS=(git python3 python3-pip libglib2.0-dev libsmbclient-dev libcups2-dev libgirepository1.0-dev libcurl4-openssl-dev libssl-dev)

	for PKG in "${PKGS[@]}"; do

		apt install -fyq "${PKG}"

	done

}

installPyPkgs(){

	PY_PKGS=(pyserial obd)

	for PY_PKG in "${PY_PKGS[@]}"; do

		pip3 install "${PY_PKG}"

	done

}


installPyOBD(){

	git clone https://github.com/barracuda-fsh/pyobd.git
	cd pyobd

	pip3 install -r requirements.txt
	python3 pyobd.py

}

checkRoot
installAptPkgs
installPyPkgs
installPyOBD
