#!/bin/bash

## start virtual CAN interface.

viface='vcan0'

modules=( 'can' 'vcan' )


if [[ "${EUID}"  -ne '0' ]]; then

	echo 'run me as root!'
	exit 1

fi

if ! lsmod | grep 'can' > /dev/null;then

	for module in "${modules[@]}";do

		modprobe ${module} || exit 1

	done

fi


if ifconfig "${viface}" > /dev/null; then

	echo "${viface} already loaded!"

else

	ip link add dev "${viface}" type vcan

	ip link set up "${viface}"

fi

icsim_dir='./ICSim'

if [[ -e "${icsim_dir}" ]]; then

	if { cd ${icsim_dir}&&./controls -m bmw -l 2 -X -d "${viface}"&; } ; then

		echo "CAN traffic emulation started!"

	else

		exit 1

	fi

fi
