#!/bin/python3

import obd
import time

# Function to connect to the OBD-II adapter
def connect_obd():
    connection = obd.OBD(portstr="/dev/ttyUSB0", baudrate=115200, fast=True, timeout=10)
#
#    if connection.is_connected():
#        print("Successfully connected to the vehicle.")
#    else:
#        print("Failed to connect to the vehicle. Check if the device is connected properly.")
#        exit()
#
    return connection
#
# Function to fetch and display all supported sensor data
def fetch_and_display_data(connection):
    for command in connection.supported_commands:
        response = connection.query(command)  # send the command, and parse the response

        if not response.is_null() and response.value is not None:  # check if there is a valid response
            print(f"{command.name}: {response.value}")



def main():
    connection = connect_obd()
    fetch_and_display_data(connection)

if __name__ == "__main__":
    main()
